/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import { secureConfig } from './config/secure.config';

const awsExports = {
    "aws_project_region": secureConfig.aws.region,
    "aws_cognito_identity_pool_id": secureConfig.aws.identityPoolId,
    "aws_cognito_region": secureConfig.aws.region,
    "aws_user_pools_id": secureConfig.aws.userPoolId,
    "aws_user_pools_web_client_id": secureConfig.aws.userPoolWebClientId,
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};

export default awsExports;
